/**
 * Regression guard: QZ signing private keys must never be committed.
 *
 * Background: apps/print-bridge/certs/private-key.pem, .../ca-key.pem and
 * public/signing/private-key.pem were tracked since the initial commit. The
 * private key is the credential that authorises silent printing for every
 * tenant — anyone holding it can forge signatures that QZ Tray accepts.
 *
 * Two independent guards: the .gitignore rules (so a local re-add is caught
 * early) and the git index itself (so a `git add -f` cannot slip through).
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const REPO_ROOT = join(__dirname, "..", "..", "..", "..");
const GITIGNORE = readFileSync(join(REPO_ROOT, ".gitignore"), "utf-8");

const REQUIRED_IGNORE_RULES = [
  "/apps/print-bridge/certs/private-key.pem",
  "/apps/print-bridge/certs/ca-key.pem",
  "/apps/print-bridge/certs/tenants/*/private-key.pem",
  "/apps/print-bridge/certs/tenants/*/ca-key.pem",
  "/apps/web/public/signing/private-key.pem",
  "/public/signing/private-key.pem",
];

test("gitignore covers every QZ signing private key", () => {
  for (const rule of REQUIRED_IGNORE_RULES) {
    assert.ok(
      GITIGNORE.split("\n").some((line) => line.trim() === rule),
      `.gitignore must contain "${rule}" — signing keys are generated by ` +
        "apps/print-bridge/scripts/gen-tenant-pki.sh and must never be committed",
    );
  }
});

test("no signing private key is tracked by git", () => {
  let tracked: string;
  try {
    tracked = execFileSync("git", ["ls-files"], { cwd: REPO_ROOT, encoding: "utf-8" });
  } catch {
    // Not a git checkout (e.g. exported tarball) — the ignore rules above
    // are the only guard available there.
    return;
  }

  const keyFiles = tracked
    .split("\n")
    .map((file) => file.trim())
    .filter((file) => file.toLowerCase().endsWith(".pem"))
    .filter((file) => /(^|\/)[^/]*key[^/]*\.pem$/i.test(file));

  assert.deepEqual(
    keyFiles,
    [],
    "private keys are tracked by git — run `git rm --cached <file>`; " +
      "the material is public from now on and must be rotated",
  );
});
