module.exports = {
  apps: [
    {
      name: "gustopos-api",
      cwd: "/srv/gustopos",
      script: "npm",
      args: "run start --workspace @gustopos/api",
      env: {
        NODE_ENV: "production",
        PORT: "11901",
        DATABASE_URL: "postgresql://postgres:gustopos_dev_password@localhost:5432/gustopos",
        JWT_SECRET: "dev-secret-key-change-in-production-min-32-chars",
        REDIS_URL: "redis://127.0.0.1:6379",
        CORS_ORIGIN: "https://test.franksbar.it,http://65.108.42.45:11900,http://65.108.42.45:80,http://localhost:11900,http://localhost:80",
        PRINT_BRIDGE_URL: "http://127.0.0.1:11905/print",
        PRINT_BRIDGE_SECRET: "9110db1ba224fc20e36555f2b5167159aef6d2479e1a85069c6a4b0aa15d3a19",
        ACCESS_TOKEN_TTL_SECONDS: "900",
        REFRESH_TOKEN_TTL_SECONDS: "604800",
      },
      max_memory_restart: "512M",
      autorestart: true,
      time: true,
    },
    {
      name: "gustopos-web",
      cwd: "/srv/gustopos",
      script: "npm",
      args: "run dev --workspace @gustopos/web",
      env: {
        NODE_ENV: "development",
        PORT: "11900",
      },
      max_memory_restart: "512M",
      autorestart: true,
      time: true,
    },
    {
      name: "gustopos-print-bridge",
      cwd: "/srv/gustopos",
      script: "npm",
      args: "run start --workspace @gustopos/print-bridge",
      env: {
        NODE_ENV: "production",
        PRINT_BRIDGE_PORT: "11905",
        PRINT_BRIDGE_SPOOL_DIR: "/var/spool/gustopos-print",
        API_URL: "http://127.0.0.1:11901",
        PRINT_BRIDGE_ID: "bridge_main",
        PRINT_BRIDGE_NAME: "Main Bridge (kitchen/bar/cashier)",
        PRINT_BRIDGE_AREAS: "kitchen,bar,cashier",
        PRINT_BRIDGE_PRINTERS: "[]",
        PRINT_BRIDGE_SECRET: "9110db1ba224fc20e36555f2b5167159aef6d2479e1a85069c6a4b0aa15d3a19",
        PRINT_BRIDGE_HEARTBEAT_MS: "30000",
        PRINT_BRIDGE_CLAIM_MS: "3000",
        PRINT_BRIDGE_CLAIM_BATCH: "10",
      },
      max_memory_restart: "256M",
      autorestart: true,
      time: true,
    },
  ],
};
