package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"time"
)

// ─── Self-update ──────────────────────────────────────────────────────────
// The agent checks the deploy origin's public /downloads/version.json (written
// by `make publish-downloads`) and, when a newer release exists, downloads the
// artifact matching this OS/arch, verifies its SHA-256, replaces the running
// binary and restarts itself. Only the configured, trusted API origin is
// contacted and every artifact is checksum-verified against that same origin.

const (
	updateCheckEvery  = 6 * time.Hour
	updateHTTPTimeout = 30 * time.Second
)

// UpdateManifest mirrors apps/web/public/downloads/version.json.
type UpdateManifest struct {
	App       string           `json:"app"`
	Version   string           `json:"version"`
	Artifacts []UpdateArtifact `json:"artifacts"`
}

type UpdateArtifact struct {
	File   string `json:"file"`
	SHA256 string `json:"sha256"`
	Size   int64  `json:"size"`
}

var updateHTTPClient = &http.Client{Timeout: updateHTTPTimeout}

// parseVersion turns "v0.11.2" / "0.11.2" into [major, minor, patch].
func parseVersion(value string) ([3]int, bool) {
	var out [3]int
	value = strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(value), "v"))
	if value == "" {
		return out, false
	}
	parts := strings.Split(value, ".")
	for i := 0; i < len(parts) && i < 3; i++ {
		// Tolerate prerelease/build metadata on the patch component (0.11.2-rc1).
		digits := parts[i]
		if idx := strings.IndexAny(digits, "-+"); idx >= 0 {
			digits = digits[:idx]
		}
		number, err := strconv.Atoi(strings.TrimSpace(digits))
		if err != nil {
			return out, false
		}
		out[i] = number
	}
	return out, true
}

// isNewerVersion reports whether remote is strictly newer than current.
func isNewerVersion(remote, current string) bool {
	r, okR := parseVersion(remote)
	c, okC := parseVersion(current)
	if !okR || !okC {
		return false
	}
	for i := 0; i < 3; i++ {
		if r[i] != c[i] {
			return r[i] > c[i]
		}
	}
	return false
}

// artifactName is the release file for the current OS/arch, matching the names
// generated by scripts/publish-downloads.sh.
func artifactName() string {
	name := fmt.Sprintf("gustopos-print-agent-%s-%s", runtime.GOOS, runtime.GOARCH)
	if runtime.GOOS == "windows" {
		name += ".exe"
	}
	return name
}

func fetchUpdateManifest(base string) (*UpdateManifest, error) {
	url := strings.TrimRight(base, "/") + "/downloads/version.json"
	resp, err := updateHTTPClient.Get(url)
	if err != nil {
		return nil, fmt.Errorf("fetch update manifest: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 300 {
		return nil, fmt.Errorf("update manifest HTTP %d", resp.StatusCode)
	}
	var manifest UpdateManifest
	if err := json.NewDecoder(io.LimitReader(resp.Body, 1<<20)).Decode(&manifest); err != nil {
		return nil, fmt.Errorf("decode update manifest: %w", err)
	}
	return &manifest, nil
}

func findArtifact(manifest *UpdateManifest, file string) (*UpdateArtifact, bool) {
	for i := range manifest.Artifacts {
		if manifest.Artifacts[i].File == file {
			return &manifest.Artifacts[i], true
		}
	}
	return nil, false
}

func downloadToFile(url, dest string) error {
	resp, err := updateHTTPClient.Get(url)
	if err != nil {
		return fmt.Errorf("download update: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 300 {
		return fmt.Errorf("download update HTTP %d", resp.StatusCode)
	}
	part := dest + ".part"
	file, err := os.OpenFile(part, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o755)
	if err != nil {
		return fmt.Errorf("create update temp: %w", err)
	}
	if _, err := io.Copy(file, resp.Body); err != nil {
		file.Close()
		os.Remove(part)
		return fmt.Errorf("write update temp: %w", err)
	}
	if err := file.Close(); err != nil {
		os.Remove(part)
		return err
	}
	if err := os.Rename(part, dest); err != nil {
		os.Remove(part)
		return err
	}
	return nil
}

func fileSHA256(path string) (string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer file.Close()
	hash := sha256.New()
	if _, err := io.Copy(hash, file); err != nil {
		return "", err
	}
	return hex.EncodeToString(hash.Sum(nil)), nil
}

// updateInProgress guards against overlapping checks (ticker + manual command).
var updateInProgress = make(chan struct{}, 1)

// checkForUpdate runs one update cycle. It returns nil when already current or
// when auto-update is disabled; on a successful apply it restarts the process
// (and therefore does not normally return).
func (a *Agent) checkForUpdate() error {
	if !a.cfg.autoUpdateEnabled() {
		return nil
	}
	select {
	case updateInProgress <- struct{}{}:
		defer func() { <-updateInProgress }()
	default:
		return nil // a check is already running
	}

	manifest, err := fetchUpdateManifest(a.api.SignBase)
	if err != nil {
		return err
	}
	if !isNewerVersion(manifest.Version, version) {
		return nil
	}
	artifact, ok := findArtifact(manifest, artifactName())
	if !ok {
		log.Printf("update %s available but no artifact for %s/%s", manifest.Version, runtime.GOOS, runtime.GOARCH)
		return nil
	}
	// Never let a manifest field escape the downloads directory.
	file := filepath.Base(artifact.File)
	if file != artifact.File || file == "." || file == ".." {
		return fmt.Errorf("update manifest has an unsafe artifact name %q", artifact.File)
	}

	exe, err := os.Executable()
	if err != nil {
		return fmt.Errorf("resolve executable: %w", err)
	}
	dest := filepath.Join(filepath.Dir(exe), ".gustopos-print-agent.update")
	log.Printf("update available: %s -> %s (%s)", version, manifest.Version, file)

	if err := downloadToFile(a.api.SignBase+"/downloads/bin/"+file, dest); err != nil {
		return err
	}
	sum, err := fileSHA256(dest)
	if err != nil {
		os.Remove(dest)
		return fmt.Errorf("hash update: %w", err)
	}
	if !strings.EqualFold(sum, artifact.SHA256) {
		os.Remove(dest)
		return fmt.Errorf("update checksum mismatch (got %s, want %s)", sum, artifact.SHA256)
	}

	if a.runtime != nil {
		a.runtime.Status.SetConfig(a.cfg)
	}
	log.Printf("update verified, installing %s and restarting", manifest.Version)
	if err := replaceAndRestart(dest); err != nil {
		os.Remove(dest)
		return fmt.Errorf("install update: %w", err)
	}
	os.Exit(0)
	return nil
}
